"use client";

import { useState, useEffect } from "react";
import Navbar from "@/components/Navbar";
import { MOCK_REPORTS, ReportEntry, RiskLevel } from "@/lib/types";
import { getReports } from "@/lib/api";
import {
  FileText,
  Download,
  ChevronDown,
  ChevronUp,
  Shield,
  AlertTriangle,
  Clock,
  Phone,
  TrendingUp,
  RefreshCw,
} from "lucide-react";
import { format } from "date-fns";
import toast from "react-hot-toast";

type FilterType = "all" | "SCAM" | "SUSPICIOUS" | "SAFE";

const VERDICT_CONFIG: Record<RiskLevel, { color: string; bg: string; border: string; icon: string; label: string }> = {
  SCAM: { color: "text-danger", bg: "bg-danger/10", border: "border-danger/20", icon: "🔴", label: "SCAM" },
  SUSPICIOUS: { color: "text-warning", bg: "bg-warning/10", border: "border-warning/20", icon: "🟡", label: "SUSPICIOUS" },
  SAFE: { color: "text-safe", bg: "bg-safe/10", border: "border-safe/20", icon: "🟢", label: "SAFE" },
};

function RiskBadge({ score, verdict }: { score: number; verdict: RiskLevel }) {
  const config = VERDICT_CONFIG[verdict];
  return (
    <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full ${config.bg} border ${config.border}`}>
      <span className="text-sm">{config.icon}</span>
      <span className={`text-xs font-bold ${config.color}`}>{config.label}</span>
      <span className={`text-xs font-mono ${config.color} opacity-70`}>{score}</span>
    </div>
  );
}

function ReportCard({ report }: { report: ReportEntry }) {
  const [expanded, setExpanded] = useState(false);
  const config = VERDICT_CONFIG[report.verdict];

  const generateReport = () => {
    const content = `
CYBERCRIME EVIDENCE REPORT
Generated by GuardianAngel AI
Date: ${new Date().toLocaleString()}
================================

INCIDENT DETAILS
Date/Time: ${format(new Date(report.date), "PPpp")}
Caller Number: ${report.callerNumber}
Call Duration: ${report.duration}
Verdict: ${report.verdict}
Risk Score: ${report.riskScore}/100
Voice Clone Probability: ${Math.round(report.voiceCloneProbability * 100)}%

DETECTED THREATS
${report.threats.map((t) => `- ${t.label} (${t.confidence}% confidence)`).join("\n")}

TRANSCRIPT EXCERPT
${report.transcript.map((t) => `[${t.time}] ${t.text}`).join("\n")}

This report was generated automatically by GuardianAngel AI.
For cybercrime reporting: https://cybercrime.gov.in
National Helpline: 1930
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `cybercrime-report-${report.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Cybercrime report downloaded!");
  };

  return (
    <div className={`glass rounded-2xl border ${expanded ? config.border : "border-white/5"} overflow-hidden transition-all`}>
      {/* Main row */}
      <div
        className="flex items-center gap-4 p-5 cursor-pointer hover:bg-white/2 transition-all"
        onClick={() => setExpanded(!expanded)}
      >
        <div className={`w-12 h-12 rounded-xl ${config.bg} border ${config.border} flex items-center justify-center text-xl shrink-0`}>
          {config.icon}
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-3 flex-wrap">
            <p className="text-white font-semibold text-sm font-mono">{report.callerNumber}</p>
            {report.callerName && (
              <span className="text-text-muted text-xs">({report.callerName})</span>
            )}
          </div>
          <div className="flex items-center gap-3 mt-1 text-xs text-text-muted">
            <span className="flex items-center gap-1">
              <Clock className="w-3 h-3" />
              {format(new Date(report.date), "MMM d, yyyy · h:mm a")}
            </span>
            <span className="flex items-center gap-1">
              <Phone className="w-3 h-3" />
              {report.duration}
            </span>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <RiskBadge score={report.riskScore} verdict={report.verdict} />
          {expanded ? (
            <ChevronUp className="w-4 h-4 text-text-muted" />
          ) : (
            <ChevronDown className="w-4 h-4 text-text-muted" />
          )}
        </div>
      </div>

      {/* Expanded details */}
      {expanded && (
        <div className="border-t border-white/5 p-5 space-y-5 animate-fade-in-up">
          {/* Stats row */}
          <div className="grid grid-cols-3 gap-3">
            <div className="glass rounded-xl p-3 text-center border border-white/5">
              <div className={`text-xl font-bold font-mono ${config.color}`}>{report.riskScore}</div>
              <div className="text-text-muted text-xs">Risk Score</div>
            </div>
            <div className="glass rounded-xl p-3 text-center border border-white/5">
              <div className="text-xl font-bold font-mono text-danger">
                {Math.round(report.voiceCloneProbability * 100)}%
              </div>
              <div className="text-text-muted text-xs">Voice Clone</div>
            </div>
            <div className="glass rounded-xl p-3 text-center border border-white/5">
              <div className="text-xl font-bold font-mono text-warning">{report.threats.length}</div>
              <div className="text-text-muted text-xs">Threats</div>
            </div>
          </div>

          {/* Threats */}
          {report.threats.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-white text-xs font-semibold uppercase tracking-wider">Detected Threats</h4>
              <div className="space-y-1.5">
                {report.threats.map((threat) => (
                  <div key={threat.id} className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <div className="w-1.5 h-1.5 rounded-full bg-danger" />
                      <span className="text-text-muted">{threat.label}</span>
                    </div>
                    <span className="text-danger font-mono font-bold">{threat.confidence}%</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Transcript excerpt */}
          {report.transcript.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-white text-xs font-semibold uppercase tracking-wider">Transcript Excerpt</h4>
              <div className="space-y-1.5 font-mono text-xs">
                {report.transcript.slice(0, 3).map((entry, i) => (
                  <div key={i} className="flex gap-3">
                    <span className="text-text-muted w-10 shrink-0">{entry.time}</span>
                    <span className={entry.hasKeyword ? "text-danger" : "text-text-muted"}>
                      {entry.text}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Actions */}
          <div className="flex gap-3 pt-2">
            <button
              onClick={generateReport}
              className="flex-1 py-2.5 rounded-xl border border-primary/20 text-primary text-xs font-semibold hover:bg-primary/10 transition-all flex items-center justify-center gap-2"
            >
              <Download className="w-3.5 h-3.5" />
              Generate Cybercrime Report
            </button>
            <button
              onClick={() => toast("Opening cybercrime portal...", { icon: "🌐" })}
              className="flex-1 py-2.5 rounded-xl border border-white/10 text-text-muted text-xs font-semibold hover:bg-white/5 transition-all flex items-center justify-center gap-2"
            >
              <FileText className="w-3.5 h-3.5" />
              Report to Cybercrime.gov.in
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default function ReportsPage() {
  const [filter, setFilter] = useState<FilterType>("all");
  const [reports, setReports] = useState<ReportEntry[]>(MOCK_REPORTS);
  const [loading, setLoading] = useState(false);

  // Try to load real reports from backend on mount
  useEffect(() => {
    const loadReports = async () => {
      setLoading(true);
      try {
        const data = await getReports();
        if (data && data.length > 0) {
          setReports(data);
        }
      } catch {
        // Backend not available — use mock data silently
      } finally {
        setLoading(false);
      }
    };
    loadReports();
  }, []);

  const refresh = async () => {
    setLoading(true);
    try {
      const data = await getReports();
      setReports(data);
      toast.success("Reports refreshed");
    } catch {
      toast.error("Could not reach backend — showing cached data");
    } finally {
      setLoading(false);
    }
  };

  const filtered = reports.filter(
    (r) => filter === "all" || r.verdict === filter
  );

  const stats = {
    total: reports.length,
    scams: reports.filter((r) => r.verdict === "SCAM").length,
    suspicious: reports.filter((r) => r.verdict === "SUSPICIOUS").length,
    safe: reports.filter((r) => r.verdict === "SAFE").length,
  };

  const exportAll = () => {
    const data = JSON.stringify(reports, null, 2);
    const blob = new Blob([data], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `guardianangel-all-reports-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("All reports exported!");
  };

  return (
    <div className="min-h-screen bg-background grid-bg">
      <Navbar />

      <div className="pt-20 pb-8 max-w-7xl mx-auto px-4 sm:px-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="font-display text-2xl font-bold text-white mb-1">Scam History</h1>
            <p className="text-text-muted text-sm">
              Complete analysis history and evidence reports
            </p>
          </div>
          <button
            onClick={refresh}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 rounded-lg border border-primary/20 text-primary text-sm font-semibold hover:bg-primary/10 transition-all disabled:opacity-50"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </button>
          <button
            onClick={exportAll}
            className="flex items-center gap-2 px-4 py-2 rounded-lg border border-primary/20 text-primary text-sm font-semibold hover:bg-primary/10 transition-all"
          >
            <Download className="w-4 h-4" />
            Export All Reports
          </button>
        </div>

        {/* Stats row */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {[
            { label: "Total Scans", value: stats.total, color: "text-primary", icon: TrendingUp },
            { label: "Scams Blocked", value: stats.scams, color: "text-danger", icon: AlertTriangle },
            { label: "Suspicious", value: stats.suspicious, color: "text-warning", icon: Shield },
            { label: "Safe Calls", value: stats.safe, color: "text-safe", icon: Shield },
          ].map((stat) => {
            const Icon = stat.icon;
            return (
              <div key={stat.label} className="glass rounded-2xl border border-white/5 p-5 text-center space-y-2">
                <Icon className={`w-6 h-6 ${stat.color} mx-auto`} />
                <div className={`text-3xl font-display font-bold ${stat.color}`}>{stat.value}</div>
                <div className="text-text-muted text-xs">{stat.label}</div>
              </div>
            );
          })}
        </div>

        {/* Filter tabs */}
        <div className="flex gap-2 p-1 rounded-xl bg-surface border border-white/5 mb-6 w-fit">
          {(["all", "SCAM", "SUSPICIOUS", "SAFE"] as FilterType[]).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-4 py-2 rounded-lg text-sm font-semibold transition-all ${
                filter === f
                  ? f === "SCAM"
                    ? "bg-danger/15 text-danger border border-danger/20"
                    : f === "SUSPICIOUS"
                    ? "bg-warning/15 text-warning border border-warning/20"
                    : f === "SAFE"
                    ? "bg-safe/15 text-safe border border-safe/20"
                    : "bg-primary/15 text-primary border border-primary/20"
                  : "text-text-muted hover:text-white"
              }`}
            >
              {f === "all" ? "All" : f}
              <span className="ml-2 text-xs opacity-60">
                ({f === "all" ? stats.total : reports.filter((r) => r.verdict === f).length})
              </span>
            </button>
          ))}
        </div>

        {/* Reports list */}
        <div className="space-y-4">
          {filtered.length === 0 ? (
            <div className="glass rounded-2xl border border-white/5 p-12 text-center space-y-3">
              <FileText className="w-10 h-10 text-text-muted mx-auto opacity-40" />
              <p className="text-text-muted">No reports found for this filter</p>
            </div>
          ) : (
            filtered.map((report) => <ReportCard key={report.id} report={report} />)
          )}
        </div>

        {/* Cybercrime info */}
        <div className="mt-8 glass rounded-2xl border border-primary/10 p-6 space-y-3">
          <h3 className="text-white font-semibold text-sm flex items-center gap-2">
            <Shield className="w-4 h-4 text-primary" />
            Report Cybercrime in India
          </h3>
          <div className="grid sm:grid-cols-3 gap-4 text-sm">
            <div className="space-y-1">
              <p className="text-primary font-semibold">National Helpline</p>
              <p className="text-white font-mono text-lg">1930</p>
              <p className="text-text-muted text-xs">24/7 cybercrime helpline</p>
            </div>
            <div className="space-y-1">
              <p className="text-primary font-semibold">Online Portal</p>
              <p className="text-white text-sm">cybercrime.gov.in</p>
              <p className="text-text-muted text-xs">File complaint online</p>
            </div>
            <div className="space-y-1">
              <p className="text-primary font-semibold">Evidence Required</p>
              <p className="text-text-muted text-xs">Call recording, screenshots, transaction details, GuardianAngel report</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
